### ISSUE TITLE
Implement filter for `dataFormatId`

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/api#257]
Dear @StephenCzarnecki , do you think you can implement a filter for [dataFormatId](https://github.com/ise621/building-envelope-data/blob/a94320a92018c48a44315bc0297e6fd96ef4acd4/apis/metabase.graphql#L1170)? Then @simon-wacker could implement it in the [metabase frontend](https://www.buildingenvelopedata.org/).

**Comment by RDmitchell** [comment]
Priority = 3

**Comment by christoph-maurer** [comment]
I used the query
```
query {
  allOpticalData(
    where: {
      resources: {
        some: {
          dataFormatId: { equalTo: "e021cf20-e887-4dce-ad27-35da70cec472" }
        }
      }
    }
  ) {
    nodes {
      componentId
      resourceTree {
        root {
          value {
            locator
            dataFormatId
          }
        }
      }
    }
  }
}
```
to check the results and the response looks good. 

@simon-wacker Can you please implement the filter for `dataFormatId` in the metabase frontend?

**Comment by simon-wacker** [comment]
Implemented in https://github.com/building-envelope-data/metabase/commit/cc40ba788e55690bff86ef5cf77e8631a2bc5114 (not yet deployed though).
