### ISSUE TITLE
Implement equal to in the queries

### ISSUE THREAD

**Issue by RDmitchell** [building-envelope-data/api#270]
When people search https://www.buildingenvelopedata.org/data/optical for `Nearnormal hemispherical solar transmittance
 is equal to 0.91`, they should receive the data sets of three components of IGSDB.

Priority = 1

**Comment by StephenCzarnecki** [comment]
@RDmitchell I started by implementing a query for exact equality as stated in @christoph-maurer's notes from the meeting but that does not return anything for a query on records with a solar transmittance of exactly 0.91.  When I use a graphql query to see what is very close to 0.91 I get three records with tsol = 0.9097287, 0.9103985, and 0.9096357.  The values displayed on the web interface are rounded.

If I query for any of those values  using the exact digits returned by Django I get the correct record.  So far I do not see a way built in to Django to change how it does the filtering on floating point equality.  

It seems we would have to decide on some other comparison to get a query for 0.91 to return exactly those three results.  
E.g We could decide that "equalTo" really means within 1% (or some other epsilon) or some other rule we decide on.  But depending on the rule it may not always match what is displayed on the website either.  If matching what is displayed on the website is the goal I can look into what rounding rules are it is using and see about constructing a similar filter.

Here are some queries and responses as examples.  Note that while there are some queries using "equalTo" that is currently only implemented locally and is using the default equality filtering from Django:
Query for all records with tsol in [0.909, 0.911]:
```yaml
query {
  allOpticalData(
    where: {  nearnormalHemisphericalSolarTransmittances: { some:{greaterThanOrEqualTo: 0.909, lessThanOrEqualTo:0.911}}}
  ) {
    nodes {
      name
      resourceTree {
        root {
          value {
            locator
          }
        }
      },
      nearnormalHemisphericalSolarTransmittances
    }
  }
}
```

Response: 
```yaml
{
  "data": {
    "allOpticalData": {
      "nodes": [
        {
          "name": "Planibel Clearvision 3 mm",
          "resourceTree": {
            "root": {
              "value": {
                "locator": "https://igsdb-icon.herokuapp.com/api/v1/products/4791/?json_format=buildingenvelopedata.org"
              }
            }
          },
          "nearnormalHemisphericalSolarTransmittances": [
            0.9097287
          ]
        },
        {
          "name": "Low-Iron EUROWHITE NG 3 mm",
          "resourceTree": {
            "root": {
              "value": {
                "locator": "https://igsdb-icon.herokuapp.com/api/v1/products/8331/?json_format=buildingenvelopedata.org"
              }
            }
          },
          "nearnormalHemisphericalSolarTransmittances": [
            0.9103985
          ]
        },
        {
          "name": "Generic thin glass 0.5 mm",
          "resourceTree": {
            "root": {
              "value": {
                "locator": "https://igsdb-icon.herokuapp.com/api/v1/products/11452/?json_format=buildingenvelopedata.org"
              }
            }
          },
          "nearnormalHemisphericalSolarTransmittances": [
            0.9096357
          ]
        }
      ]
    }
  }
}
```

Query for record using same precision as database:
```yaml
query {
  allOpticalData(
    where: {  nearnormalHemisphericalSolarTransmittances: { some:{equalTo: 0.9097287}}}
  ) {
    nodes {
      name
      resourceTree {
        root {
          value {
            locator
          }
        }
      },
      nearnormalHemisphericalSolarTransmittances
    }
  }
}
```

Response returns exactly that record:
```yaml
{
  "data": {
    "allOpticalData": {
      "nodes": [
        {
          "name": "Planibel Clearvision 3 mm",
          "resourceTree": {
            "root": {
              "value": {
                "locator": "https://igsdb-icon.herokuapp.com/api/v1/products/4791/?json_format=buildingenvelopedata.org"
              }
            }
          },
          "nearnormalHemisphericalSolarTransmittances": [
            0.9097287
          ]
        }
      ]
    }
  }
}
```

But using anything less than the full 0.9097287 does not work.
```yaml
query {
  allOpticalData(
    where: {  nearnormalHemisphericalSolarTransmittances: { some:{equalTo: 0.909729}}}
  ) {
    nodes {
      name
      resourceTree {
        root {
          value {
            locator
          }
        }
      },
      nearnormalHemisphericalSolarTransmittances
    }
  }
}
```
Response:
```yaml
{
  "data": {
    "allOpticalData": {
      "nodes": []
    }
  }
}
```

**Comment by christoph-maurer** [comment]
@StephenCzarnecki For me, the current implementation of `equalTo` (without an epsilon) is sufficient. Thank you for implementing it!

**Comment by christoph-maurer** [comment]
I queried the metabase frontend and the backend for `nearnormalHemisphericalSolarTransmittances equalTo 0.9097287`. Both return the the same data set as the IGSDB backend.
