### ISSUE TITLE
Rename `ise621` to `building-envelope-data`?

### ISSUE THREAD

**Issue by simon-wacker** [building-envelope-data/api#276]
The four projects of the organization `ise621` are all related to `building-envelope-data`. I would thus just call the organization `building-envelope-data`, rename the project `building-envelope-data` to `schema`, and leave the other project names as is. What do you think @christoph-maurer ?

**Comment by simon-wacker** [comment]
Additional Note: An alternative to the project name `schema` is `api`. The project currently consists of two API specifications in the form of GraphQL Schemas and a data schema in the form of mutliple JSON Schemas.

**Comment by christoph-maurer** [comment]
I think it's a good idea to rename `ise621` to `building-envelope-data` and `building-envelope-data` to `api`. @simon-wacker How would we update the links in files like README.md and CONTRIBUTING.md in all four repositories?

**Comment by simon-wacker** [comment]
I'd use SED: `sed -i -e "s_ise621/building-envelope-data_ise621/api_g" -e "s/ise621/building-envelope-data/g" *.md` and then check whether everything is as intended with `git diff`.-----"Christoph Maurer" ***@***.***> schrieb: -----An: "ise621/building-envelope-data" ***@***.***>Von: "Christoph Maurer" ***@***.***>Datum: 06.12.2021 11:45Kopie: "Simon Wacker" ***@***.***>, "Mention" ***@***.***>Betreff: Re: [ise621/building-envelope-data] Rename `ise621` to `building-envelope-data`? (Issue #276)
I think it's a good idea to rename ise621 to building-envelope-data and building-envelope-data to api. @simon-wacker How would we update the links in files like README.md and CONTRIBUTING.md in all four repositories?

**Comment by simon-wacker** [comment]
I'd use SED: `sed -i -e "s_ise621/building-envelope-data_ise621/api_g" -e "s/ise621/building-envelope-data/g" *.md` and then check whether everything is as intended with `git diff`.
