### ISSUE TITLE
Does the visualization show the entire api?

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/api#313]
When I look at https://graphql-kit.com/graphql-voyager/?url=https://www.buildingenvelopedata.org/graphql/ , I don't see for example the field `OpticalDataPropositionInput`. @simon-wacker Do you know why?

**Comment by simon-wacker** [comment]
It seems to me that parameter types are not shown in the graph. You can however in the left navigation click on `Query`, then on `Database` (to the right of the query `database`), then on `allData`, and then on `DataPropositionInput`, which opens a drawer with the interface's/type's fields. So, the graph is complete in the sense that it shows all the data that can be queried. It does not show the parameterization though.

**Comment by christoph-maurer** [comment]
Thank you, @simon-wacker !
