### ISSUE TITLE
Provide thickness of a component in the product data network

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/api#328]
@danielmcquillen In many cases, planners need a glass pane with a certain thickness and required optical properties. This is a very simple geometric information. However, geometric data can also be complex such as a CAD file. We have therefore created the domain `geometricData`

[thicknessGlassPane.json](https://github.com/building-envelope-data/api/blob/a9ce6beca5dae053da8e23f7c072c0204cf600b0/tests/valid/geometricData/thicknessGlassPane.json#L5-L6) is an example of a tiny JSON file including only the thickness. It is valid against the schema [geometricData.json](https://github.com/building-envelope-data/api/blob/a9ce6beca5dae053da8e23f7c072c0204cf600b0/schemas/geometricData.json#L53).

We have added `geometricData` to the [API specification](https://github.com/building-envelope-data/api/blob/c9c2c3d9098d3f9a2a0698cc7c76bf2c30b41d91/apis/database.graphql#L1269-L1292). [tutorial.graphql](https://github.com/building-envelope-data/api/blob/c9c2c3d9098d3f9a2a0698cc7c76bf2c30b41d91/queries/database/tutorial.graphql#L148-L162) includes a query as example.

Several partners of EQWIN-P are interested in using the thickness of components for their planning software. This issue has therefore a higher priority than for example #323 .

**Comment by danielmcquillen** [comment]
@christoph-maurer Noted. The IGSDBv2 API has a similar concept, which we use to store various forms of geometric data for different shading subtypes....e.g. perforated screen

<img width="514" alt="image" src="https://github.com/building-envelope-data/api/assets/119496/6be726bf-ab02-44af-8b52-b460d6d63375">

In the short-term, it looks like you're asking for the graphql representation in the IGSDBv2 to repeat the base thickness value in this new `GeometricData` node...is that right?

I imagine that when @RDmitchell returns we could have a larger discussion about geometric data in both API formats.

**Comment by danielmcquillen** [comment]
@christoph-maurer How would this addition affect the JSON representation of the product in `bed-format`?

Here is what `clr-3` looks like currently:
```
"data": [
  { 
      "componentCharacteristics": {
         "surface": "prime"
         "symmetries": "azimuthalAngleInvariance"
         "dataPoints": [...]
    },
     { 
      "componentCharacteristics": {
         "surface": "nonPrime"
         "symmetries": "azimuthalAngleInvariance"
         "dataPoints": [...]
    }
]
```

With this addition are you saying `clr-3` would look like this?

```
"data": [
  { 
    "componentCharacteristics": {
      "surface": "prime"
      "symmetries": "azimuthalAngleInvariance"
      "dataPoints": [...]
    },
    { 
      "componentCharacteristics": {
      "surface": "nonPrime"
      "symmetries": "azimuthalAngleInvariance"
      "dataPoints": [...]
    }
    {
      "dimensions": {
        "installed": [
            {
            "thickness": 0.004
            } 
        ]
      }
    }
]
```




```

**Comment by danielmcquillen** [comment]
@christoph-maurer 

Thanks for providing more details. Ok, I can create an endpoint for `allGeometricData` similar to `allOpticalData` which will return thickness information.

However, I'm unclear on the example you provided: what kind of data is provided in the "dataPoints" attribute? Should I lave those as empty arrays for now?

Also, I'm confused about the keys and objects shown in the above example...I don't think the keys and their objects are correct and maybe a comma is missing? (Only pointing this out as I want to make sure I understand the shape of the data correctly).

Your example shows one sample object of potentially many in the array keyed by "data." In this example object, is the second key/dictionary meant to be "componentCharacteristics"? If so there's an extra "{" above it? Or is it meant to be nested?

So not sure how to read this example.

Perhaps what you meant is something like this?

```
"data": [
    { 
        "componentCharacteristics": [
            {
                "surface": "prime"
                "symmetries": "azimuthalAngleInvariance"
                "dataPoints": [...]
            },
            { 
                "surface": "nonPrime"
                "symmetries": "azimuthalAngleInvariance"
                "dataPoints": [...]
            }
        ],
        "dimensions": {
            "installed": [
                {
                    "thickness": 0.004
                } 
            ]
        }
    }
    ...
    (... other products...)
    ....

]
```


Just curious: why is "installed" an array of objects with a single "thickness" key rather that one object with multiple keys? In what case would there be multiple objects in an array? Wouldn't it be simpler to a single object with multiple key/values?..

```
"dimensions": {
    "installed": {
        "thickness": 0.004
        ... (other installed properties) ... 
    }
}
```


If you can clarify the above structure I can have a go at creating an `allGeometricData` endpoint.

**Comment by christoph-maurer** [comment]
In my last comment, I cited

> "data": [ ...

and tried to explain why this is **not** what we need. All optical data sets must be valid against the schema [opticalData.json](https://github.com/building-envelope-data/api/blob/c9c2c3d9098d3f9a2a0698cc7c76bf2c30b41d91/schemas/opticalData.json). All geometric data sets must be valid against the schema [geometricData](https://github.com/building-envelope-data/api/blob/c9c2c3d9098d3f9a2a0698cc7c76bf2c30b41d91/schemas/geometricData.json). There will be no data sets which include both optical and geometric data. There will be an optical data set like 
https://github.com/building-envelope-data/api/blob/c9c2c3d9098d3f9a2a0698cc7c76bf2c30b41d91/tests/valid/opticalData/igsdbExample196.json and a separate geometric data set like https://github.com/building-envelope-data/api/blob/c9c2c3d9098d3f9a2a0698cc7c76bf2c30b41d91/tests/valid/geometricData/thicknessGlassPane.json . But be careful with such examples. The schemas are the most important part. They must contain all information which is needed to implement the data sets. Please let me know about each description in the schema which is not explained well enough to understand. I have to improve them so that the next software developer can understand them.

For example, the title of ["installed"](https://github.com/building-envelope-data/api/blob/c9c2c3d9098d3f9a2a0698cc7c76bf2c30b41d91/schemas/geometricData.json#L39-L63) is
```
          "title": "This geometric definition of the dimensions refers to the installation of the component in a building envelope and a view perpendicular to the building envelope. The dimensions can be used to define a bounding box which includes all parts of the component. If a component can be installed in different ways, more than one set of dimensions can be defined.",
```
Does the last sentence answer your question? Can I explain it better? For glass panes and shading layers in IGSDB, I think we need only one item in the array "installed". However, there are building envelope components which can be installed in different ways. For example a rectangular window, which can be mounted vertically/portrait or horizontally/landscape. In this case, the array "installed" can contain two items.

 > Also, why would "dimensions" be conceptually outside of "component characteristics"...isn't the dimension a "characteristic" so to speak? (just curious as to your thinking.)

In the context of optical data sets, ["componentCharacteristics"](https://github.com/building-envelope-data/api/blob/c9c2c3d9098d3f9a2a0698cc7c76bf2c30b41d91/schemas/opticalData.json#L114-L180) defines the `"Parameters for optical measurements and simulations."` They provide additional information about how the the optical data was determined. Geometric data should be separate. For example, the manufacturer can provide and sign digitally the geometric data set. The optical data set may refer to a standard of NFRC as "method" and be signed digitally by NFRC as "approval". Charlie and I have been talking about methods and approvals with many others for a long time. They are in the backlog to be implement in the future.

@danielmcquillen Which of my paragraphs are helpful and where can I do more?

**Comment by christoph-maurer** [comment]
One funded partner of our project and one associated partner needs the thickness of the components for their implementations.
