### ISSUE TITLE
Provide `type` and `subtype` from IGSDB in the product data network

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/api#340]
@simon-wacker For each data set, IGSDB has the key `type` with the possible values `glazing` or`shading`. It has also the key `subtype` with the possible values `monolithic`, `coating`, `coated glass`,  `film`, `applied film`, `interlayer` and `laminate`. For at least one of our associated partners, it would be very helpful to have these values available in the GraphQL-API of the IGSDB. When you succeed with the [thickness](https://github.com/building-envelope-data/api/issues/328), can you easily add the two keys?

@danielmcquillen @RDmitchell Would it be ok for you if we do this?

**Comment by christoph-maurer** [comment]
More information about the `subtypes` is available at https://igsdb-v2.herokuapp.com/docs/help/whats-changed/type-subtype . Thank you @danielmcquillen !

**Comment by simon-wacker** [comment]
@christoph-maurer When you run the query

```
query AllData {
  allOpticalData {
    edges {
      node {
        type
        subtype
      }
    }
  }
}
```

against the IGSDB, for example after signing in on https://igsdb-v2.herokuapp.com/graphql/, you receive `type` and `subtype` of all data. Is that just what you were asking for?

**Comment by christoph-maurer** [comment]
Yes, this is what we currently need. Thank you @simon-wacker !
