### ISSUE TITLE
Read and check the optical schemas and examples

### ISSUE THREAD

**Issue by simon-wacker** [building-envelope-data/api#42]
In GitLab by @christoph-maurer on Jul 28, 2020, 16:02

@bruno.bueno @helen.rose.wilson Please do the following things
1. read the schemas and examples and check them for possible issues
1. create several realistic BSDF examples which cover together all keys defined by optical.json
1. if possible, create examples which should not be allowed and verify whether they are invalid against the schema
1. check if all optical data can be represented according to the schema or extensions of the schema are needed

Your work has the following targets
1. validate the schema by trying it for the first time
1. validate that other persons can learn to use the schema
1. create examples for convincing use cases for follow-up projects
1. create examples for documentation and dissemination so that others can learn more quickly
1. create examples which serve as a check regarding uncontrolled changes of the schema

Please let @christoph-maurer know whenever you need anything. @helen.rose.wilson plans to work on the topic in August and informs @bruno.bueno about her progress who works on the topic in September.

**Comment by christoph-maurer** [comment]
Our working group has read and checked the optical schemas and examples with the available resources. Additional comments and reviews are welcome anytime.
